-- Generado por scripts/generar-seed.mjs — no editar a mano.
-- 188 conceptos. Ejecutar despues de 01_esquema.sql y 02_politicas.sql.

insert into conceptos (codigo, categoria, nombre, unidad, precio, taxonomia, aplicabilidad, fuente, fecha_ref) values
  ('BT-001','Instalación eléctrica BT (materiales)','Cable CA THHW-LS 400 kcmil','m',785.76,'fuente'::taxonomia_dato,'Base','distribuidor mayorista (línea Vinanel/Condumex)','2026-07'),
  ('BT-002','Instalación eléctrica BT (materiales)','Cable CA THHW-LS 4/0 AWG','m',480.97,'fuente'::taxonomia_dato,'Base','distribuidor mayorista','2026-07'),
  ('BT-003','Instalación eléctrica BT (materiales)','Cable CC RHW-2/XHHW-2 4/0 AWG 1000 V','m',601.25,'supuesto'::taxonomia_dato,'Base','Sin precio público confiable; corrección de espec v3 SC','2026-07'),
  ('BT-004','Instalación eléctrica BT (materiales)','Terminal bimetálica 400 kcmil','pza',249,'fuente'::taxonomia_dato,'Base','COEL/Burndy','2026-07'),
  ('BT-005','Instalación eléctrica BT (materiales)','Terminal bimetálica 4/0 AWG','pza',114,'fuente'::taxonomia_dato,'Base','COEL/Burndy','2026-07'),
  ('BT-006','Instalación eléctrica BT (materiales)','Terminal bimetálica 2/0 AWG','pza',84,'fuente'::taxonomia_dato,'Base','COEL/Burndy','2026-07'),
  ('BT-007','Instalación eléctrica BT (materiales)','Tubo PAD 4 pulg','m',82.67,'fuente'::taxonomia_dato,'Base','distribuidor mayorista (tramo 6.10 m)','2026-07'),
  ('BT-008','Instalación eléctrica BT (materiales)','Tubo PAD 3 pulg','m',56.48,'fuente'::taxonomia_dato,'Base','distribuidor mayorista (tramo 6.10 m)','2026-07'),
  ('BT-009','Instalación eléctrica BT (materiales)','Cinchos nylon UV 400 mm','pza',2,'supuesto'::taxonomia_dato,'Base','Precio de mercado, no verificado','2026-07'),
  ('BT-010','Instalación eléctrica BT (materiales)','Cinchos nylon UV 200 mm','pza',1,'supuesto'::taxonomia_dato,'Base','Precio de mercado, no verificado','2026-07'),
  ('BT-011','Instalación eléctrica BT (materiales)','Cartucho etiquetas DYMO Rhino 19 mm','pza',331.51,'validado'::taxonomia_dato,'Base','Cotización de proveedor (11/mar/2026), a nombre de Beyond','2026-03'),
  ('BT-012','Instalación eléctrica BT (materiales)','Cartucho etiquetas DYMO Rhino 12 mm','pza',308.54,'validado'::taxonomia_dato,'Base','Cotización de proveedor (11/mar/2026)','2026-03'),
  ('BT-013','Instalación eléctrica BT (materiales)','Cinta aislante','pza',35,'supuesto'::taxonomia_dato,'Base','Precio de mercado, no verificado','2026-07'),
  ('BT-014','Instalación eléctrica BT (materiales)','Plumón permanente','pza',25,'supuesto'::taxonomia_dato,'Base','Precio de mercado, no verificado','2026-07'),
  ('BT-015','Instalación eléctrica BT (materiales)','Termorretráctil 1 1/2 pulg','m',95,'supuesto'::taxonomia_dato,'Base','Precio de mercado, no verificado','2026-07'),
  ('BT-016','Instalación eléctrica BT (materiales)','Termorretráctil 1 1/4 pulg','m',75,'supuesto'::taxonomia_dato,'Base','Precio de mercado, no verificado','2026-07'),
  ('BT-017','Instalación eléctrica BT (materiales)','Termorretráctil 3/4 pulg','m',35,'supuesto'::taxonomia_dato,'Base','Precio de mercado, no verificado','2026-07'),
  ('BT-018','Instalación eléctrica BT (materiales)','Juego de anclaje mecánico gabinete','juego',250,'supuesto'::taxonomia_dato,'Base','Precio de mercado, no verificado','2026-07'),
  ('BT-019','Instalación eléctrica BT (materiales)','Juego de fijación 1/4','juego',50,'supuesto'::taxonomia_dato,'Base','Precio de mercado, no verificado','2026-07'),
  ('BT-020','Instalación eléctrica BT (materiales)','Etiqueta vinil adherible','pza',300,'supuesto'::taxonomia_dato,'Base','Precio de mercado, no verificado','2026-07'),
  ('BT-021','Instalación eléctrica BT (materiales)','Supresor de transitorios cat. C','pza',90000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $120,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('BT-022','Instalación eléctrica BT (materiales)','Supresores de transitorios cat. B','lote',80000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $110,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('BT-023','Instalación eléctrica BT (materiales)','Transformador seco auxiliar 45 kVA','pza',85000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $130,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('BT-024','Instalación eléctrica BT (materiales)','Tablero auxiliar 220/127 V','pza',35000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $80,000 (criterio de ingeniería) Precio observado…','2026-06'),
  ('BT-025','Instalación eléctrica BT (materiales)','Canalización y alimentadores auxiliares','lote',640000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $600,000 en dos partidas (criterio de ingeniería)…','2026-06'),
  ('BT-026','Instalación eléctrica BT (materiales)','Paros de emergencia y señalización eléctrica','lote',120000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $160,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('BT-027','Instalación eléctrica BT (materiales)','Pruebas y comisionamiento','lote',30000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $180,000 (criterio de ingeniería); escalar por ta…','2026-06'),
  ('BT-028','Instalación eléctrica BT (materiales)','As-built, etiquetado y manual O&M','lote',40000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $90,000 (criterio de ingeniería) Precio observado…','2026-06'),
  ('CFE-001','Suministrador CFE','UVIE (verificación NOM-001-SEDE)','servicio',38000,'fuente'::taxonomia_dato,'Base','Ref. cotización de mercado (feb/2026); Referencia interna sugiere $220k p/ 2 MVA','2026-02'),
  ('CFE-002','Suministrador CFE','Trámite de interconexión CFE (RGD)','servicio',52000,'validado'::taxonomia_dato,'Base','Acuerdo interno v7 (base ref. cotización de mercado $42k)','2026-07'),
  ('CFE-003','Suministrador CFE','Gestoría CFE y proyecto MT','servicio',100000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $180,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('CFE-004','Suministrador CFE','Aportación de obra CFE','servicio',1500000,'supuesto'::taxonomia_dato,'Condicional','Referencia interna allowance $1,500,000 p/ 2 MVA — confirmar con oficio CFE Precio observado…','2026-06'),
  ('CFE-005','Suministrador CFE','Depósito en garantía CFE','servicio',1001263,'supuesto'::taxonomia_dato,'Condicional','Referencia interna extrapolado $6,200,000 p/ 2 MVA desde dato de 750 kVA Precio observado en…','2026-06'),
  ('CFE-006','Suministrador CFE','Estudios, factibilidad y libranzas','servicio',250000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería para estudios, libranzas y acompañamiento de energización.','2026-06'),
  ('DPL-001','Diseño, ingeniería, permisos y licencias','Ingeniería de detalle y expediente (EPC)','servicio',85000,'validado'::taxonomia_dato,'Base','Presupuesto definido por Beyond (acuerdo v5 SC); rango defendible $70-100k','2026-07'),
  ('DPL-002','Diseño, ingeniería, permisos y licencias','Proyecto ejecutivo completo','servicio',350000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $650,000 p/ 17 cargadores (criterio de ingeniería…','2026-06'),
  ('DPL-003','Diseño, ingeniería, permisos y licencias','Uso de suelo y gestión municipal','servicio',150000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $100,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('DPL-004','Diseño, ingeniería, permisos y licencias','Licencia de construcción','servicio',450000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $250,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('DPL-005','Diseño, ingeniería, permisos y licencias','Permiso de construcción (gestión EPC)','servicio',25000,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC (varía mucho por municipio)','2026-07'),
  ('DPL-006','Diseño, ingeniería, permisos y licencias','Licencia de operación','servicio',280000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $180,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('DPL-007','Diseño, ingeniería, permisos y licencias','Protección civil y DRO','servicio',145000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $180,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('DPL-008','Diseño, ingeniería, permisos y licencias','Estudios eléctricos especializados','servicio',280000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería sobre alcance de estudios para subestación de 1 MVA o más.','2026-06'),
  ('DPL-009','Diseño, ingeniería, permisos y licencias','Topografía y mecánica de suelos','servicio',160000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería para levantamiento, mecánica de suelos e interferencias.','2026-06'),
  ('DPL-010','Diseño, ingeniería, permisos y licencias','Memorias de cálculo estructural','servicio',120000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería para memorias estructurales de cubierta y bases.','2026-06'),
  ('EVSE-001','Cargadores (EVSE)','Cargador DC 240 kW','pza',575505,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $900,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('EVSE-002','Cargadores (EVSE)','Cargador DC 120 kW','pza',437909,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $550,000 (criterio ingeniería; original $237,139…','2026-06'),
  ('EVSE-003','Cargadores (EVSE)','Cargador DC 60 kW','pza',320000,'supuesto'::taxonomia_dato,'Condicional','Referencia interna de proyecto de estación propia. Criterio de ingeniería,','2026-06'),
  ('EVSE-004','Cargadores (EVSE)','Cargador AC 7 kW','pza',22000,'supuesto'::taxonomia_dato,'Condicional','Referencia interna de proyecto de estación propia. Criterio de ingeniería,','2026-06'),
  ('EVSE-005','Cargadores (EVSE)','Flete, importación y maniobras EVSE','lote',130000,'supuesto'::taxonomia_dato,'Condicional','Provisión por equipo derivada de una referencia interna de lote.','2026-06'),
  ('EVSE-006','Cargadores (EVSE)','Configuración OCPP y puesta en servicio','lote',250000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería para integración de protocolo y puesta en servicio.','2026-06'),
  ('EVSE-007','Cargadores (EVSE)','Refacciones críticas iniciales','lote',90000,'supuesto'::taxonomia_dato,'Opcional','Provisión por equipo derivada de una referencia interna de lote. Criterio de ingeniería,','2026-06'),
  ('EVSE-008','Cargadores (EVSE)','Garantía extendida / soporte de arranque','lote',300000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería para soporte de arranque de operación. Criterio de ingeniería,','2026-06'),
  ('EVSE-009','Cargadores (EVSE)','Cargador DC 80 kW','pza',396667,'allowance'::taxonomia_dato,'Condicional','No existe referencia para esta potencia. Interpolación lineal entre las referencias de 60 y…','2026-08'),
  ('EVSE-010','Cargadores (EVSE)','Cargador DC 180 kW','pza',725000,'allowance'::taxonomia_dato,'Condicional','No existe referencia para esta potencia. Interpolación lineal entre las referencias de 120 y…','2026-08'),
  ('FEE-001','Indirectos, fee y contingencia','Management fee / indirectos','%',10,'supuesto'::taxonomia_dato,'Base','Porcentaje de referencia sobre partidas con fee aplicable. Ajustar por dirección.','2026-06'),
  ('FEE-002','Indirectos, fee y contingencia','Contingencia','%',25,'supuesto'::taxonomia_dato,'Base','Porcentaje de referencia para estimado clase conceptual.','2026-06'),
  ('GE-001','Gestión de energía','EMS / balanceo dinámico','sistema',300000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $750,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('GE-002','Gestión de energía','Sistema de medición MEM','sistema',500000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería, referencia interna $650,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('GE-003','Gestión de energía','Monitoreo de calidad de energía','sistema',45000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería, referencia interna $280,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('GE-004','Gestión de energía','Medidores por alimentador','lote',350000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería para medición por alimentador e integración. Criterio de ingeniería,','2026-06'),
  ('GE-005','Gestión de energía','BESS (almacenamiento)','sistema',1207125,'fuente'::taxonomia_dato,'Opcional','Referencia externa de mercado 2026: 180 a 320 dólares por kWh instalado para almacenamiento…','2026-06'),
  ('GE-006','Gestión de energía','Módulo BESS 125 kW / 161 kWh','pza',1207125,'fuente'::taxonomia_dato,'Condicional','Referencia externa de mercado 2026: 180 a 320 dólares por kWh instalado para almacenamiento…','2026-08'),
  ('GE-007','Gestión de energía','Integración BESS-EMS-FV','lote',96570,'allowance'::taxonomia_dato,'Condicional','Provisión de 8% del costo del módulo de almacenamiento, por integración de control,','2026-08'),
  ('GE-008','Gestión de energía','Obra civil y adecuaciones BESS','lote',60356,'allowance'::taxonomia_dato,'Condicional','Provisión de 5% del costo del módulo de almacenamiento, por obra civil, contención,','2026-08'),
  ('INS-001','Mano de obra e instalación','Instalación de Power Cabinet','pza',25000,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC (sin cotización de instalador)','2026-07'),
  ('INS-002','Mano de obra e instalación','Instalación de dispensador','pza',8000,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('INS-003','Mano de obra e instalación','Instalación de tablero de protecciones','pza',15000,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('INS-004','Mano de obra e instalación','Instalación de transformador','pza',20000,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC (ajuste v7)','2026-07'),
  ('INS-005','Mano de obra e instalación','Instalación de canalizaciones','m',20.4,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('INS-006','Mano de obra e instalación','Instalación de cables CA y CD','m',302.64,'validado'::taxonomia_dato,'Base','Regla interna Beyond (derivado de márgenes de cable 45%)','2026-07'),
  ('INS-007','Mano de obra e instalación','Instalación de sistema de tierras','m',134.08,'validado'::taxonomia_dato,'Base','Regla interna Beyond','2026-07'),
  ('INS-008','Mano de obra e instalación','Instalación de equipo de comunicación','lote',18000,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('INS-009','Mano de obra e instalación','Instalación de sistema CCTV cableado','lote',38000,'supuesto'::taxonomia_dato,'Condicional','Referencia interna de proyecto EPC (supuesto razonado v9)','2026-07'),
  ('LEG-001','Legal y corporativo','Constitución de empresa','servicio',12000,'supuesto'::taxonomia_dato,'Opcional','Referencia interna (criterio de ingeniería)','2026-06'),
  ('LEG-002','Legal y corporativo','Libros y actas','servicio',5000,'supuesto'::taxonomia_dato,'Opcional','Referencia interna (criterio de ingeniería)','2026-06'),
  ('LEG-003','Legal y corporativo','Emisión de acciones','servicio',5000,'supuesto'::taxonomia_dato,'Opcional','Referencia interna (criterio de ingeniería)','2026-06'),
  ('LEG-004','Legal y corporativo','Contratos y revisión legal','servicio',80000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna (criterio de ingeniería)','2026-06'),
  ('MED-001','Medición','Nicho de medición','pza',27000,'fuente'::taxonomia_dato,'Base','Base ref. cotización de mercado $22k + $5k herrerías (decisión v8)','2026-07'),
  ('MT-001','Media tensión y transformación','Transformador pedestal 750 kVA','pza',635250,'allowance'::taxonomia_dato,'Condicional','Regla de $847/kVA aplicada a 750 kVA. No se encontró precio público para transformadores ped…',''),
  ('MT-002','Media tensión y transformación','Transformador pedestal 2,000 kVA','pza',1694000,'allowance'::taxonomia_dato,'Condicional','Regla de $847/kVA aplicada a 2,000 kVA. Sin precio público disponible.','2026-06'),
  ('MT-003','Media tensión y transformación','Celda de MT 23 kV','lote',1300000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería para celda de seccionamiento, protección y maniobra en 23 kV.','2026-06'),
  ('MT-004','Media tensión y transformación','Tablero general BT alta capacidad','pza',1200000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $1,850,000 (criterio de ingeniería) Precio observ…','2026-06'),
  ('MT-005','Media tensión y transformación','Tableros derivados','lote',750000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería para veinte circuitos derivados. Escalar por número de circuitos.','2026-06'),
  ('MT-006','Media tensión y transformación','Interruptores derivados (juego)','lote',850000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería para diecisiete equipos. Escalar por circuitos y verificar cada inter…','2026-06'),
  ('MT-007','Media tensión y transformación','Alimentador principal TR-tablero','servicio',650000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $1,200,000 p/ 3,200 A (criterio de ingeniería) Pr…','2026-06'),
  ('MT-008','Media tensión y transformación','Cable XLP Al 1/0 25 kV','m',250,'supuesto'::taxonomia_dato,'Condicional','CAPEX Referencia interna original, fuente no documentada','2026-06'),
  ('MT-009','Media tensión y transformación','Terminales tipo codo 200 A 25 kV','pza',3300,'supuesto'::taxonomia_dato,'Condicional','CAPEX Referencia interna original, fuente no documentada','2026-06'),
  ('MT-010','Media tensión y transformación','Apartarrayos 21 kV','pza',3200,'supuesto'::taxonomia_dato,'Condicional','CAPEX Referencia interna original, fuente no documentada','2026-06'),
  ('MT-011','Media tensión y transformación','Cortacircuito fusible CCF 27 kV','pza',3300,'supuesto'::taxonomia_dato,'Condicional','CAPEX Referencia interna original, fuente no documentada','2026-06'),
  ('MT-012','Media tensión y transformación','Banco de ductos MT 3 vías','m',1800,'fuente'::taxonomia_dato,'Condicional','Ref. real cotización de mercado (feb/2026)','2026-02'),
  ('MT-013','Media tensión y transformación','Gabinete de medición MT','pza',32600,'supuesto'::taxonomia_dato,'Condicional','CAPEX Referencia interna original, fuente no documentada','2026-06'),
  ('MT-014','Media tensión y transformación','Medición CFE en MT (adecuaciones)','lote',450000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería. La especificación la fija la zona del suministrador.','2026-06'),
  ('MT-015','Media tensión y transformación','Transformador pedestal 1,500 kVA','pza',1270500,'allowance'::taxonomia_dato,'Condicional','Regla de $847/kVA aplicada a 1,500 kVA: punto medio entre dos referencias internas que difie…','2026-08'),
  ('MT-016','Media tensión y transformación','Transformador pedestal 2,500 kVA','pza',1485000,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-017','Media tensión y transformación','Tablero general BT 3x5000 A','pza',1200000,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-018','Media tensión y transformación','Poste MT hincado','pza',95000,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-019','Media tensión y transformación','Terminal exterior contráctil en frío 25 kV','pza',3300,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-020','Media tensión y transformación','Conector tipo inserto 200/220 A 25 kV','pza',2800,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-021','Media tensión y transformación','Adaptador de tierra 220 A 25 kV','pza',1100,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-022','Media tensión y transformación','Neutro corrido CUD No. 2','m',200,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-023','Media tensión y transformación','Bota termocontráctil 4" 3 vías','pza',1500,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-024','Media tensión y transformación','Conector perico 1/0','pza',600,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-025','Media tensión y transformación','Estribo para línea viva 3/0','pza',500,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-026','Media tensión y transformación','Bajante a tierra MT','m',500,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-027','Media tensión y transformación','Alambre de cobre Cal. 4','kg',650,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-028','Media tensión y transformación','Herrajes de sujeción MT (paquete)','juego',2390,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-029','Media tensión y transformación','Marbetes de identificación de fases','pza',250,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-030','Media tensión y transformación','Cable THHW-LS Cu 3/0 (600 V)','m',520,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-031','Media tensión y transformación','Muerto para equipo de medición','pza',14000,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-032','Media tensión y transformación','Correderas, ménsulas y neopreno','juego',1300,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-033','Media tensión y transformación','Soldadura exotérmica cadwell','pza',500,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-034','Media tensión y transformación','Conductores desnudos y zapatas (lote)','lote',4620,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('MT-035','Media tensión y transformación','Tubo conduit pared delgada 2" con accesorios','lote',4100,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('OC-001','Obra civil','Registro eléctrico polimérico 40x40x40','pza',2200,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('OC-002','Obra civil','Registro eléctrico polimérico 80x80x80','pza',5500,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('OC-003','Obra civil','Cinta de señalización subterránea','m',8,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('OC-004','Obra civil','Zanja 50x100 cm con reposición de concreto','m',950,'fuente'::taxonomia_dato,'Base','Composición: tabulador CDMX 2025 + ref. cotización de mercado banco ductos $1,800/m','2026-07'),
  ('OC-005','Obra civil','Zanja 30x50 cm','m',350,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC — EN REVISIÓN: con reposición real daría ~$550-600/m','2026-07'),
  ('OC-006','Obra civil','Base y registro transformador pedestal','pza',25000,'fuente'::taxonomia_dato,'Base','Ref. cotización de mercado (feb/2026)','2026-02'),
  ('OC-007','Obra civil','Excavación para base de transformador','pza',20000,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('OC-008','Obra civil','Cimentación Power Unit','pza',25000,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('OC-009','Obra civil','Cimentación dispensador','pza',15000,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('OC-010','Obra civil','Tope de cajón','pza',650,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('OC-011','Obra civil','Pintura señalización horizontal','m2',180,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('OC-012','Obra civil','Guardacolumnas de hule','pza',850,'supuesto'::taxonomia_dato,'Opcional','Referencia interna de proyecto EPC','2026-07'),
  ('OC-013','Obra civil','Lámpara solar de patio','pza',2800,'supuesto'::taxonomia_dato,'Opcional','Referencia interna de proyecto EPC','2026-07'),
  ('OC-014','Obra civil','Piso de patio de carga (lote)','lote',650000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería para piso de patio por lote. Con superficie medida usar los unitarios…','2026-06'),
  ('OC-015','Obra civil','Cuarto eléctrico / área técnica','lote',1100000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $650,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('OC-016','Obra civil','Techumbre / cubierta de estación','lote',836000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería, referencia interna $900,000 consolidado (criterio de ingeniería) Pre…','2026-06'),
  ('OC-017','Obra civil','Drenaje pluvial y protecciones','lote',300000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería para drenaje pluvial, bolardos y protección física.','2026-06'),
  ('OC-018','Obra civil','Demolición de piso de concreto reforzado','m2',832,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('OC-019','Obra civil','Piso de concreto f''c=200, 10 cm, escobillado','m2',750,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('OC-020','Obra civil','Guarnición de concreto','m',286,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('OC-021','Obra civil','Techumbre metálica de área de carga','m2',15200,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('OC-022','Obra civil','Registro RM TB3 (1.16 x 1.16 x 0.90)','pza',22000,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('OC-023','Obra civil','Reparación de cubierta existente y branding','servicio',125000,'supuesto'::taxonomia_dato,'Opcional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('OC-024','Obra civil','Lámparas y contactos de patio','pza',2000,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('OC-025','Obra civil','Protección de cajón de carga (paquete)','servicio',35000,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('OC-026','Obra civil','Zanjado y banco de ductos (lote)','lote',475000,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('PC-001','Protección civil','Extintor PQS ABC','pza',1000,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('PC-002','Protección civil','Señalética ruta de evacuación','pza',180,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('PC-003','Protección civil','Señalética de alta tensión','pza',150,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('PC-004','Protección civil','Señalética de extintor','pza',120,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('PC-005','Protección civil','Pintura de punto de reunión','pza',2500,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('PC-006','Protección civil','Botiquín industrial','pza',1200,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('SB-001','Señalización y branding','Señalética operativa y de seguridad','lote',98200,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $250,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('SB-002','Señalización y branding','Tótem / identificación principal','lote',500000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería, referencia interna $300,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('SB-003','Señalización y branding','Muro verde','lote',150000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería, referencia interna $120,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('SB-004','Señalización y branding','Pintura de piso y branding horizontal','lote',165000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $120,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('SB-005','Señalización y branding','Instrucciones de usuario y QR','lote',35000,'supuesto'::taxonomia_dato,'Base','Criterio de ingeniería, referencia interna $80,000 (criterio de ingeniería) Precio observado…','2026-06'),
  ('SDE-001','Sala de espera','Adecuación de sala de espera','lote',250000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería, referencia interna $300,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('SDE-002','Sala de espera','Estructura interior','lote',450000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería, referencia interna $250,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('SDE-003','Sala de espera','Mobiliario y equipamiento','lote',50000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería, referencia interna $150,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('SDE-004','Sala de espera','Baños (adecuación)','pza',55000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería, referencia interna $140,000 c/u (criterio de ingeniería) Precio obse…','2026-06'),
  ('SDE-005','Sala de espera','Climatización','lote',120000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería para climatización de sala de espera. Criterio de ingeniería,','2026-06'),
  ('SDE-006','Sala de espera','Equipamiento menor y TV','lote',10000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería, referencia interna ~$85,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('SDE-007','Sala de espera','Escalera','servicio',75000,'supuesto'::taxonomia_dato,'Opcional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('SDE-008','Sala de espera','Pintura y acabados complementarios','servicio',45000,'supuesto'::taxonomia_dato,'Opcional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026),','2026-08'),
  ('SFV-001','Sistema fotovoltaico','Módulo FV mono bifacial 635 W','pza',3395.7,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026); precio +10% por instrucción de d…','2026-08'),
  ('SFV-002','Sistema fotovoltaico','Inversor de cadena 125 kW','pza',116187.5,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026); precio +10% por instrucción de d…','2026-08'),
  ('SFV-003','Sistema fotovoltaico','Estructura de montaje FV','kWp',2156.77,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026); precio +10% por instrucción de d…','2026-08'),
  ('SFV-004','Sistema fotovoltaico','Materiales eléctricos FV CD y CA','kWp',3125.97,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026); precio +10% por instrucción de d…','2026-08'),
  ('SFV-005','Sistema fotovoltaico','Instalación y mano de obra FV','kWp',1708,'allowance'::taxonomia_dato,'Condicional','Provisión de 15% del suministro fotovoltaico por kWp.','2026-08'),
  ('SFV-006','Sistema fotovoltaico','Servicio EPC/D FV (indirectos)','servicio',137500,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026); precio +10% por instrucción de d…','2026-08'),
  ('SFV-007','Sistema fotovoltaico','Interconexión FV y medidor bidireccional','servicio',82500,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026); precio +10% por instrucción de d…','2026-08'),
  ('SFV-008','Sistema fotovoltaico','UVIE fotovoltaico','servicio',137500,'supuesto'::taxonomia_dato,'Condicional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026); precio +10% por instrucción de d…','2026-08'),
  ('SFV-009','Sistema fotovoltaico','Referencia integrada FV ($/kWp)','kWp',11964.15,'supuesto'::taxonomia_dato,'Opcional','CAPEX proyecto de hub de referencia (hoja CAPEX, ago/2026); precio +10% por instrucción de d…','2026-08'),
  ('TEL-001','Telecom, monitoreo y seguridad','Terminal UTP RJ45','pza',8,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('TEL-002','Telecom, monitoreo y seguridad','Bota de protección RJ45','pza',5,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('TEL-003','Telecom, monitoreo y seguridad','Cable RS485 1 par','m',9,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('TEL-004','Telecom, monitoreo y seguridad','Cable UTP cat. 6 blindado','m',14,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('TEL-005','Telecom, monitoreo y seguridad','Cable uso rudo 2x14 AWG','m',28,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('TEL-006','Telecom, monitoreo y seguridad','Tubería EMT 1/2 pulg (con accesorios)','m',120,'validado'::taxonomia_dato,'Base','Dato interno Beyond (alcance confirmado por dirección, v2 SC)','2026-07'),
  ('TEL-007','Telecom, monitoreo y seguridad','Gabinete de site','pza',3500,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('TEL-008','Telecom, monitoreo y seguridad','Nodo de red','nodo',14800,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $18,000 (criterio de ingeniería) Precio observado…','2026-06'),
  ('TEL-009','Telecom, monitoreo y seguridad','Plumas de seguridad y acceso','pza',30000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería, referencia interna $90,000 (criterio de ingeniería) Precio observado…','2026-06'),
  ('TEL-010','Telecom, monitoreo y seguridad','Sistema CCTV completo (12 cám.)','sistema',56000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $220,000 (criterio de ingeniería) Precio observad…','2026-06'),
  ('TEL-011','Telecom, monitoreo y seguridad','Red industrial y respaldo','sistema',180000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería para enrutador industrial, respaldo de enlace y energía.','2026-06'),
  ('TEL-012','Telecom, monitoreo y seguridad','Alarma y seguridad de sitio','sistema',160000,'supuesto'::taxonomia_dato,'Opcional','Criterio de ingeniería para alarma, sensores y botón de pánico. Criterio de ingeniería,','2026-06'),
  ('TEL-013','Telecom, monitoreo y seguridad','Equipo de videovigilancia suministrado por el cliente','lote',0,'validado'::taxonomia_dato,'Condicional','Renglón de exclusión explícita: el equipo lo suministra el cliente,','2026-07'),
  ('TIE-001','Sistema de tierras','Cable Cu desnudo 4/0 AWG','m',400,'validado'::taxonomia_dato,'Base','Averiguación propia dirección (ref. cotización de mercado ~$300/m)','2026-07'),
  ('TIE-002','Sistema de tierras','Cable Cu desnudo 2/0 AWG','m',251,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('TIE-003','Sistema de tierras','Varilla copperweld 5/8','pza',750,'fuente'::taxonomia_dato,'Base','Ref. cotización cotización de mercado (feb/2026)','2026-02'),
  ('TIE-004','Sistema de tierras','Registro de tierras','pza',450,'supuesto'::taxonomia_dato,'Base','Referencia interna de proyecto EPC','2026-07'),
  ('TIE-005','Sistema de tierras','Conector bipartido KS20 Burndy','pza',180,'fuente'::taxonomia_dato,'Base','COEL/Burndy','2026-07'),
  ('TIE-006','Sistema de tierras','Conector GAR6429 Burndy','pza',220,'fuente'::taxonomia_dato,'Base','COEL/Burndy','2026-07'),
  ('TIE-007','Sistema de tierras','Conector bipartido KS25 Burndy','pza',260,'fuente'::taxonomia_dato,'Base','COEL/Burndy','2026-07'),
  ('TIE-008','Sistema de tierras','Sistema de tierras completo (lote)','lote',115000,'supuesto'::taxonomia_dato,'Condicional','Criterio de ingeniería, referencia interna $450,000 para 2 MVA (criterio de ingeniería) Prec…','2026-06')
on conflict (codigo) do update set
  categoria = excluded.categoria,
  nombre = excluded.nombre,
  unidad = excluded.unidad,
  fuente = excluded.fuente,
  actualizado_en = now();
-- Nota: el precio y la taxonomia NO se sobreescriben al recargar la semilla.
-- Un precio ya aprobado en la base gana sobre el del archivo.
